apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-db-pv
spec:
  storageClassName: spring-db-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8s/db/" # 로컬환경용, 클라우드에서는 제거

